
# Submit file 

# Must set the universe to Docker
universe = docker
docker_image = leojin727/hlan:latest


# set the log, error and output files 
log = hlan$(Label_Embedding)$(Freeze_emb)$(Random_emb).log
error = hlan$(Label_Embedding)$(Freeze_emb)$(Random_emb).err
output = hlan$(Label_Embedding)$(Freeze_emb)$(Random_emb).out

# set the executable to run
executable = run_python.sh
arguments = $(Label_Embedding) $(Freeze_emb) $(Random_emb) $(epoch)

# take our python script to the compute node
# the script and data are shared by multiple examples and located in a
# different directory
transfer_input_files = /home/jin263/NLP_HLAN_old/HLAN_Model/HLAN.py,/home/jin263/NLP_HLAN_old/HLAN_Model/main_run.py,/home/jin263/NLP_HLAN_old/Embeddings/train_word-emb.pt,/home/jin263/NLP_HLAN_old/Embeddings/train_code-emb.pt,/home/jin263/NLP_HLAN_old/Embeddings/test_word-emb.pt,/home/jin263/NLP_HLAN_old/Embeddings/test_code-emb.pt,/home/jin263/NLP_HLAN_old/Embeddings/word-emb_model_weights.pt,/home/jin263/NLP_HLAN_old/Embeddings/code-emb_model_weights.pt

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# We require a machine with a compatible version of the CUDA driver
require_gpus = (DriverVersion >= 10.1)

# We must request 1 CPU in addition to 1 GPU
request_cpus = 1
request_gpus = 1

# select some memory and disk space
request_memory = 20GB
request_disk = 20GB

# Opt in to using CHTC GPU Lab resources
+WantGPULab = true
# Specify short job type to run more GPUs in parallel
# Can also request "medium" or "long"
+GPUJobLength = "short"

# Tell HTCondor to run 1 instances of our job:
queue Label_Embedding, Freeze_emb, Random_emb,epoch from scenario_list.txt
